Cors, mocking, dns config reference
Kong/developer.konghq.com pull request #173
Opened 2024-12-12 21:40 UTC by Guaris

### Preview Links

### Checklist 

- [ ] Every page is page one
- [ ] Tested how-to docs. If not, note why here. 
- [ ] All pages contain metadata
- [ ] Updated [sources.yaml](https://github.com/Kong/developer.konghq.com/blob/main/tools/track-docs-changes/config/sources.yml). For more info review [track docs changes](https://github.com/Kong/developer.konghq.com/tree/main/tools/track-docs-changes)
- [ ] Any new docs link to existing docs.

2024-12-16 22:31 UTC, Guaris commented
Broken links are known they depend on #168

2024-12-17 20:20 UTC, cloudjumpercat requested changes
Left some suggestions, questions, and a few observations as I was reading the content. Let me know if you have any questions!

2024-12-18 19:08 UTC, Guaris commented on app/_includes/sections/cors-and-kong-gateway.md
> +## Understanding CORS
The example is under this with the headers being rejected.  CORS ensures that KGW doesn't deny anyone access to a resource in a proxied upstream.

2024-12-18 19:19 UTC, Guaris commented on app/_kong_plugins/mocking/index.md
> +## Behavioral Headers
I'm not a fan of it in this case. Maybe on a landing page.

2024-12-18 19:50 UTC, cloudjumpercat approved these changes

2024-12-19 10:28 UTC, fabianrbz commented on app/_kong_plugins/mocking/examples/basic-configuration.yaml
> +  Configures the mocking plugin and passes an API spec.
```suggestion
  Configures the Mocking plugin and passes an API spec.
```

2024-12-19 10:40 UTC, fabianrbz commented on app/_kong_plugins/cors/examples/basic-configuration.yaml
> +title: Configure the plugin on a Service
The targets are set by the platform based on the plugin's support, so there's no need to specify it here or [here](https://github.com/Kong/developer.konghq.com/pull/173/files#diff-5e3f90dd52aa9a4d0e8c32238de99cd3a50f4ab2fb414e9a3062d14cac230931R10).

I guess the goal of this is to allow requests from a specific domain (http://mockbin.com) and only two methods.
We could drop the headers and go with the default ones to make it simpler and rename the file, title and description to something like `Allow requests from a specific domain`

2024-12-19 10:44 UTC, fabianrbz commented on app/_kong_plugins/cors/examples/basic-configuration.yaml
> +      max_age: 3600
```suggestion
config:
  origins:
    - http://mockbin.com
  methods:
    - GET
    - POST
  headers:
    - Accept
    - Accept-Version
    - Content-Length
    - Content-MD5
    - Content-Type
    - Date
    - X-Auth-Token
  exposed_headers:
    - X-Auth-Token
  credentials: true
  max_age: 3600
```

you only need the plugin's config here

2024-12-19 10:46 UTC, fabianrbz commented on app/_kong_plugins/mocking/examples/basic-configuration.yaml
> +                      $ref: '#/components/schemas/Pet'
```suggestion
config:
  random_delay: true
  max_delay_time: 1
  min_delay_time: 0.001
  random_examples: true
  api_specification: |
    openapi: 3.0.2
    servers:
      - url: /v3
    info:
      description: |-
        This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
        Swagger at [http://swagger.io](http://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
        You can now help us improve the API whether it's by making changes to the definition itself or to the code.
        That way, with time, we can improve the API in general, and expose some of the new features in OAS3.
        Some useful links:
        - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
        - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
      version: 1.0.20-SNAPSHOT
      title: Swagger Petstore - OpenAPI 3.0
      termsOfService: 'http://swagger.io/terms/'
      contact:
        email: apiteam@swagger.io
      license:
        name: Apache 2.0
        url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
    tags:
      - name: pet
        description: Everything about your Pets
        externalDocs:
          description: Find out more
          url: 'http://swagger.io'
      - name: store
        description: Access to Petstore orders
        externalDocs:
          description: Find out more about our store
          url: 'http://swagger.io'
      - name: user
        description: Operations about user
    paths:
      /pet:
        post:
          tags:
            - pet
          summary: Add a new pet to the store
          description: Add a new pet to the store
          operationId: addPet
          responses:
            '200':
              description: Successful operation
              content:
                application/xml:
                  schema:
                    $ref: '#/components/schemas/Pet'
                application/json:
                  schema:
                    $ref: '#/components/schemas/Pet'
            '405':
              description: Invalid input
          security:
            - petstore_auth:
                - 'write:pets'
                - 'read:pets'
          requestBody:
            description: Create a new pet in the store
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Pet'
              application/xml:
                schema:
                  $ref: '#/components/schemas/Pet'
              application/x-www-form-urlencoded:
                schema:
                  $ref: '#/components/schemas/Pet'
        put:
          tags:
            - pet
          summary: Update an existing pet
          description: Update an existing pet by Id
          operationId: updatePet
          responses:
            '200':
              description: Successful operation
              content:
                application/xml:
                  schema:
                    $ref: '#/components/schemas/Pet'
                application/json:
                  schema:
                    $ref: '#/components/schemas/Pet'
            '400':
              description: Invalid ID supplied
            '404':
              description: Pet not found
            '405':
              description: Validation exception
          security:
            - petstore_auth:
                - 'write:pets'
                - 'read:pets'
          requestBody:
            description: Update an existent pet in the store
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Pet'
              application/xml:
                schema:
                  $ref: '#/components/schemas/Pet'
              application/x-www-form-urlencoded:
                schema:
                  $ref: '#/components/schemas/Pet'
```

2024-12-19 10:48 UTC, fabianrbz commented on app/_kong_plugins/mocking/examples/basic-configuration.yaml
> +description: |
The goal of this is actually to mock endpoints using an OpenAPI spec.
Can you update the file name, title and description accordingly? (something along those lines)

deck doesn't need to be part of the title, the platform generates

2024-12-19 19:15 UTC, Guaris commented on app/_kong_plugins/mocking/examples/mock-endpoints-using-an-api-spec.yaml
> +  Configures the Mocking plugin and passes a the [PetStore](https://petstore3.swagger.io/) API specification.
```suggestion
  Configures the Mocking plugin and passes the [PetStore](https://petstore3.swagger.io/) API specification.
```

2024-12-19 19:25 UTC, fabianrbz approved these changes

2024-12-19 19:47 UTC, merged