Kong Gateway: Getting started guide
Kong/developer.konghq.com pull request #174
Opened 2024-12-13 06:35 UTC by lena-larionova

### Preview Links

Very draft, do not merge.

### Checklist 

- [ ] Every page is page one
- [ ] Tested how-to docs. If not, note why here. 
- [ ] All pages contain metadata
- [ ] Updated [sources.yaml](https://github.com/Kong/developer.konghq.com/blob/main/tools/track-docs-changes/config/sources.yml). For more info review [track docs changes](https://github.com/Kong/developer.konghq.com/tree/main/tools/track-docs-changes)
- [ ] Any new docs link to existing docs.

2024-12-13 09:02 UTC, fabianrbz commented
@lena-larionova I fixed the liquid variables issue in the tldr

2024-12-17 21:27 UTC, Guaris requested changes

2024-12-17 21:27 UTC, Guaris commented on app/_how-tos/get-started-with-gateway.md
> +In the following example, you’ll use an application deployed across two different servers, or upstream targets.
```suggestion
In the following example, you’ll use an application deployed across two different hosts, or upstream targets. 
```

2024-12-17 21:27 UTC, Guaris commented on app/_how-tos/get-started-with-gateway.md
> +{{site.base_gateway}} needs to load balance across both servers, so that if one of the servers is unavailable,
```suggestion
{{site.base_gateway}} needs to load balance across the upstreams, so that if one of them is unavailable, 
```

2024-12-17 21:27 UTC, Guaris commented on app/_how-tos/get-started-with-gateway.md
> +it automatically detects the problem and routes all traffic to the working server.
```suggestion
it automatically detects the problem and routes all traffic to the working upstream.
```

2024-12-17 21:27 UTC, Guaris commented on app/_how-tos/get-started-with-gateway.md
> +    > This quickstart runs a simple Docker container to explore {{ site.base_gateway }}'s capabilities.
```suggestion
    > This quickstart runs a Docker container to explore {{ site.base_gateway }}'s capabilities. 
```

2024-12-17 21:27 UTC, Guaris commented on app/_how-tos/get-started-with-gateway.md
> +    If you want to run {{ site.base_gateway }} as a part of a production-ready API platform, start on the [Install](/gateway/install/) page.
```suggestion
    If you want to run {{ site.base_gateway }} as a part of a production-ready API platform, start with the [Install](/gateway/install/) page.
```

2024-12-17 21:27 UTC, Guaris commented on app/_how-tos/get-started-with-gateway.md
> +Services and Routes define the routing path that requests and responses will take
```suggestion
Services and Routes define the path that requests and responses will take 
```

2024-12-17 21:27 UTC, Guaris commented on app/_how-tos/get-started-with-gateway.md
> +* `url` : An argument that populates the `host`, `port`, and `path` attributes of the Service
```suggestion
* `url` : An attribute that populates the `host`, `port`, and `path` of the Service
```

2024-12-17 21:27 UTC, Guaris commented on app/_how-tos/get-started-with-gateway.md
> +request to the Service URL.
```suggestion
request to the URL defined in the service.
```

2024-12-17 21:27 UTC, Guaris commented on app/_how-tos/get-started-with-gateway.md
> +Httpbin provides an `/anything` resource which will echo back to clients information about requests made to it.
```suggestion
Httpbin provides an `/anything` resource which will return information about requests made to it.
```

2024-12-17 21:27 UTC, Guaris commented on app/_how-tos/get-started-with-gateway.md
> +will be subject to rate limit enforcement:
```suggestion
Installing the plugin globally means that *every* proxy request to {{site.base_gateway}}
will be subject to rate limit enforcement:
```

2024-12-17 21:27 UTC, Guaris commented on app/_how-tos/get-started-with-gateway.md
> +headers will indicate a cache `Hit`:
```suggestion
Within 5 seconds of the initial request, repeat the command to send an identical request. The
headers will indicate a cache `Hit`:
```

2024-12-17 21:27 UTC, Guaris commented on app/_how-tos/get-started-with-gateway.md
> +Authentication is the process of verifying that a requester has permissions to access a resource.
```suggestion
Authentication is the process of verifying that the requester has permissions to access a resource. 
```

2024-12-17 21:27 UTC, Guaris commented on app/_how-tos/get-started-with-gateway.md
> +Consumers let you identify the client that's interacting with {{site.base_gateway}}, so you need a Consumer for key authentication to work.
```suggestion
Consumers let you identify the client that's interacting with {{site.base_gateway}}. You need to create a Consumer for key authentication to work.
```

2024-12-18 17:29 UTC, Guaris approved these changes

2024-12-18 17:30 UTC, Guaris commented
lgtm shipping it

2024-12-18 17:30 UTC, merged